"""empty message

Revision ID: 483063162ca1
Revises: d2c8a6149c3c
Create Date: 2017-06-21 23:33:57.702957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483063162ca1'
down_revision = 'd2c8a6149c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('PitcherBB', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherBS', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherCG', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherER', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherGS', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherHA', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherHRA', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherHold', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherIP', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherK', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherL', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherQS', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherS', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherShutout', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('PitcherW', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'PitcherW')
    op.drop_column('score', 'PitcherShutout')
    op.drop_column('score', 'PitcherS')
    op.drop_column('score', 'PitcherQS')
    op.drop_column('score', 'PitcherL')
    op.drop_column('score', 'PitcherK')
    op.drop_column('score', 'PitcherIP')
    op.drop_column('score', 'PitcherHold')
    op.drop_column('score', 'PitcherHRA')
    op.drop_column('score', 'PitcherHA')
    op.drop_column('score', 'PitcherGS')
    op.drop_column('score', 'PitcherER')
    op.drop_column('score', 'PitcherCG')
    op.drop_column('score', 'PitcherBS')
    op.drop_column('score', 'PitcherBB')
    # ### end Alembic commands ###
