"""empty message

Revision ID: 7d680d9205fd
Revises: 24828d6ba633
Create Date: 2017-07-04 00:49:47.074064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d680d9205fd'
down_revision = '24828d6ba633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('pitcher_bs', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('pitcher_cg_per_gs', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('pitcher_hold', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('pitcher_shutout_per_gs', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('pitcher_cg', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('pitcher_shutout', sa.Float(), nullable=True))
    op.drop_column('score', 'pitcher_cg_per_gs')
    op.drop_column('score', 'pitcher_shutout_per_gs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('pitcher_shutout_per_gs', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('score', sa.Column('pitcher_cg_per_gs', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('score', 'pitcher_shutout')
    op.drop_column('score', 'pitcher_cg')
    op.drop_column('players', 'pitcher_shutout_per_gs')
    op.drop_column('players', 'pitcher_hold')
    op.drop_column('players', 'pitcher_cg_per_gs')
    op.drop_column('players', 'pitcher_bs')
    # ### end Alembic commands ###
