"""empty message

Revision ID: 860eaf7f7255
Revises: 
Create Date: 2017-06-12 21:25:43.353837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860eaf7f7255'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batters', sa.Column('avg', sa.Float(), nullable=True))
    op.add_column('batters', sa.Column('obp', sa.Float(), nullable=True))
    op.add_column('batters', sa.Column('ops', sa.Float(), nullable=True))
    op.add_column('batters', sa.Column('slg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batters', 'slg')
    op.drop_column('batters', 'ops')
    op.drop_column('batters', 'obp')
    op.drop_column('batters', 'avg')
    # ### end Alembic commands ###
