"""empty message

Revision ID: aea3270207cc
Revises: baad09685c2b
Create Date: 2017-07-04 00:32:29.620618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea3270207cc'
down_revision = 'baad09685c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('batter_errors_per_pa', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('batter_gidp_per_pa', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('batter_hbp_per_pa', sa.Float(), nullable=True))
    op.drop_column('players', 'batter_hbp')
    op.drop_column('players', 'batter_gidp')
    op.drop_column('players', 'batter_errors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('batter_errors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('batter_gidp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('batter_hbp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'batter_hbp_per_pa')
    op.drop_column('players', 'batter_gidp_per_pa')
    op.drop_column('players', 'batter_errors_per_pa')
    # ### end Alembic commands ###
