"""empty message

Revision ID: f9cbd410fdfd
Revises: 9de18a7e20ee
Create Date: 2017-06-28 17:22:09.109923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cbd410fdfd'
down_revision = '9de18a7e20ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('fantasy_points', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'fantasy_points')
    # ### end Alembic commands ###
